### ISSUE TITLE
Ipython Notebook not found

### ISSUE THREAD

**Issue by 0xzkzhao** [goulu/Goulib#2]
Hi, I was trying to read your `dxf2img` method, and when I visit your Ipython Notebook for basic info 
http://nbviewer.ipython.org/github/Goulu/Goulib/blob/master/notebook.ipynb
I found its unavailable, could you fix it?

Thank you!

**Comment by goulu** [comment]
I couldn't remember what 'dxf2img' was so I had to search and found it only in the changes.rst which is completely outdated, sorry.

The new way to do this is show in Cell 30 of http://nbviewer.ipython.org/github/Goulu/Goulib/blob/master/notebook.ipynb : 

```
Drawing('tests/drawing.dxf') // loads a .dxf and in a Drawing object and renders it on IPython
```

if you want to convert it to a different format you'd simply write:

```
Drawing('tests/drawing.dxf').save('tests/drawing.png') // or '.svg' or '.pdf'
```
