### ISSUE TITLE
How to install Goulib on Anaconda for use in a Jupyter notebook

### ISSUE THREAD

**Issue by NicHub** [goulu/Goulib#7]
Hi Phillipe,

I followed your presentation at the Microclub yesterday and I wanted to play with your notebook “python_finesses.ipynb”.

The problem I face is that this notebook requires Goulib which is not yet installed on my computer. I saw that you provide a pip installation of it, but `sudo pip install Goulib` raised an error on my Anaconda distribution (ModuleNotFoundError: No module named 'pip.req'). That is probably normal as on Anaconda I am supposed to use `conda` and not `pip`.

So the question is how to install Goulib on Anaconda for use in a Jupyter notebook.

By the way thank you for your presentation!

Nicolas

**Comment by goulu** [comment]
Hi Nicolas,
well... pip is supposed to work, but the version on https://pypi.org/project/Goulib/ is now a bit old and I know pip has changed recently... I'll check that and put a new version on pypi asap.
In the meantime you can install the latest version this way:
1. clone the Goulib repo
2. in the main goulib directory, type "pip install -r requirements.txt" to force installing the required libs
3. then "pip install -e ." to install Goulib locally
4. Have fun :-)

**Comment by goulu** [comment]
Solved in 1.9.23 released just now. it was [because of pip 10,](https://stackoverflow.com/a/49867265/1395973 ) sorry...
